### PR TITLE
(ci)Add npm script to run linter

### PR DESCRIPTION
**Pull request by elfrank**
## Image(s) or GIFs (if applicable)
This branch adds the ability to check linting by running `npm run lint`.

The configuration is present at `.eslintrc` and focuses on the
directories: src/ and test/

## Pull Request Guidelines

- [x] I have added pull requests labels which describe my contribution.
- [x] All existing tests passed.
    - [x] I have added tests to cover my changes, of which pass.
- [x] I have [compared](https://github.com/hoverinc/ray-tracing-renderer/wiki/Contributing#comparing-changes) the render output of my branch to `master`.
- [x] My code has passed the ESLint configuration for this project.
- [x] My change requires modifications to the documentation.
    - [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by lyonsno — COMMENTED** [review]
This looks great, appreciate the cleanup as well as the addition of auto-linting. One thing I noticed when running locally was that a number of linter errors occurred for files and folders I've kept around locally but not checked in to the repo. What do you think about limiting the auto lint to files that are currently tracked by git?

**Comment by elfrank** [comment]
> What do you think about limiting the auto lint to files that are currently tracked by git?

Did a quick Google search and didn't find anything about this. Have you tried this before @lyonsno ?
I don't really keep around untracked files so haven't faced before.

**Comment by lyonsno** [comment]
> Did a quick Google search and didn't find anything about this. Have you tried this before @lyonsno ?

Machete's linting seems to be working this way. It looks like machete does it via webpack, by only exporting the src/ test/ and examples/ directories? So not actually checking which files are checked in, more like an allowlist.

> I don't really keep around untracked files so haven't faced before.

I've found it to be helpful for development at times, especially when experimenting with examples and assets. I'd say it would be helpful for my workflow If I didn't need to purge or fix untracked files and folders in the repo root directory, what do you think about changing the blocklist to an allowlist?

**Comment by elfrank** [comment]
> what do you think about changing the blocklist to an allowlist?

That's a good idea @lyonsno . Take a look at [this commit](https://github.com/hoverinc/ray-tracing-renderer/pull/165/commits/8c9ebf680d3ac0a8c53a525df3991af5b27d23da). What do you think?

**Comment by lyonsno** [comment]
> > what do you think about changing the blocklist to an allowlist?
> 
> That's a good idea @lyonsno . Take a look at [this commit](https://github.com/hoverinc/ray-tracing-renderer/pull/165/commits/8c9ebf680d3ac0a8c53a525df3991af5b27d23da). What do you think?

I think that's a great solution. I'll approve.

**Review by lyonsno — APPROVED** [review]
LGTM!

**Pull request merged**
